# Generated by Django 6.1.1 on 2026-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('todos', models.ManyToManyField(blank=True, related_name='tags', to='todos.todo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
