# Generated by Django 6.1.1 on 2026-10-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
